### ISSUE TITLE
feature request - add functor application ($)

### ISSUE THREAD

**Issue by srghma** [kcsongor/typelevel-prelude#1]
hi, I see you added functor composition (.) type family, is it possible to make functor application?

**Comment by kcsongor** [comment]
Done!

**Comment by srghma** [comment]
awesome

I even added link to your repo in my old stackowerflow question https://stackoverflow.com/questions/52791746/how-to-make-dot-composition-and-dollar-application-sign-for-functors

Can I have a few questions :
- what is `->{m}` thingy?
- when this become available in haskell officially? )

**Comment by kcsongor** [comment]
Sure!

The details are available in the [paper](https://www.microsoft.com/en-us/research/uploads/prod/2019/03/ho-haskell-5c8bb4918a4de.pdf), but here's the gist:

This library works with [a fork of GHC with UnsaturatedTypeFamilies](https://gitlab.haskell.org/kcsongor/ghc/tree/unsaturated_type_families). To avoid the issues of partially applying type families, this branch assigns _different_ kinds to type constructors and type families, based on whether they're "matchable" or "unmatchable" respectively. The `->{m}` syntax
is thus a _matchability polymorphic_ arrow that accepts either type constructors of type families as arguments (with `m` being a matchability type variable).

To answer the second question, I'm currently writing a proposal for GHC about this feature -- if that proposal gets accepted, then the feature will be added to GHC.

**Comment by srghma** [comment]
ok, tnx, looking forward to the day when haskell become agda
